database:
    olap:
        driver: Prancer::Plugin::Database::Driver::Mock
        options:
            username: test
            password: test
            database: test
            hostname: /tmp
            autocommit: false
            charset: utf8
            connection_check_threshold: 10
    warehouse:
        driver: Prancer::Plugin::Database::Driver::Mock
        options:
            username: test
            password: test
            database: test
            hostname: /tmp
            autocommit: false
            charset: utf8
            connection_check_threshold: 10

